[project]
name = "comfyui-utility-suite"
description = ""
version = "1.3.0"
license = {file = "LICENSE"}

# classifiers = [
#     "Operating System :: Microsoft :: Windows",
#     "Operating System :: POSIX :: Linux",
#     "Environment :: GPU :: NVIDIA CUDA",
# ]
dependencies = []

[project.urls]
Repository = "https://github.com/tom-m-2020/ComfyUI-Utility-Suite"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/tom-m-2020/ComfyUI-Utility-Suite/wiki"
"Bug Tracker" = "https://github.com/tom-m-2020/ComfyUI-Utility-Suite/issues"

[tool.comfy]
PublisherId = "tom-m"
DisplayName = "ComfyUI-Utility-Suite"
Icon = ""
includes = []
# "requires-comfyui" = ">=0.29.0"  # ComfyUI version compatibility